---
Name: workable
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.workable:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'workable'
      defaultLifetime: 3600
