---
Name: workable
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.workable:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'workable'
      defaultLifetime: 3600
  SilverStripe\Workable\Workable:
    constructor:
      0: %$WorkableRestfulService
      1: '%$Psr\SimpleCache\CacheInterface.workable'
  WorkableRestfulService:
    class: GuzzleHttp\Client
    factory: SilverStripe\Workable\WorkableRestfulServiceFactory
SilverStripe\Workable\Workable:
  apikey: '`WORKABLE_API_KEY`'